package com.company.test;

// Generated by Hibernate Tools 3.2.0.b9 (sinosoft version)

import java.util.Date;


/**
 * PrpDConfigInfo generated by Tools.Don't edit.
 */
public class PrpDConfigInfo implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	/** 配置信息编码 */
	private Long configInfoId;
	/** 配置信息名称 */
	private String configInfoName;
	/** 登录机构代码 */
	private String loginCom;
	/** 业务归属机构代码 */
	private String comCode;
	/** 一级业务类别标识 */
	private String businessCategories1;
	/** 二级业务类别标识 */
	private String businessCategories2;
	/** 三级业务类别标识 */
	private String businessCategories3;
	/** 四级业务类别标识 */
	private String businessCategories4;
	/** 经办人代码*/
	private String handlerCode;
	/** 代理人代码*/
	private String agentCode;
	/** 协议号*/
	private String agreementNo;
	/** 创建人代代码*/
	private String creatorCode;
	/** 创建时间 */
	private Date creatorDate;
	/** 有效状标识(1:有效,0:无效) */
	private String validStatus;
	/** 是否默认配置(1:是，0：否) */
	private String isDefaultConfigInfo;
	/** 备注 */
	private String remark;
	/** 客户类别 */
	private String goalInsuredFlag;
	/** 保单归属地（地市） */
	private String cityCode;
	/** 保单归属地（县支） */
	private String countyCode;
	/**建议送修单位代码*/
	private String carShopCode;//add by yangyongjian 20170710 84新增设置添加建议送修单位  TMP-201706-025
	//add by yyj TMP-201708-15	销售人员名称、职业证号能否放到配置中 begin
	private String priorityServicerType;//优先服务商类别: 
	private String priorityServicerCode;//优先服务商名称:
	private String sales;//销售人员名称:
	private String professionalNo;//职业证号:
	private String underUnit;//网省公司/直属公司:
	//add by yyj TMP-201708-15	销售人员名称、职业证号能否放到配置中 end
	/**团车协议号*/
	private String contractNo;//add by qianxj 20170720 
	/**中介经办人*/
	private String intermediaryAgentCode;//add by yyj REQ-20180130-004 关于保监局要求投保标示制度系统改造的需求 20180320
}
